include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/core/localization/l10n/**"
    - "**/core/localization/gen/**"

linter:
  rules:
    public_member_api_docs: false
