include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - riverpod_lint
  exclude:
    - "**/core/localization/l10n/**"
    - "**/core/localization/gen/**"
    - "**/**.g.dart"
    - "**/**.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
