// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:salat_tracker/features/prayer/domain/models/prayer_day.dart';
import 'package:salat_tracker/features/prayer/domain/models/prayer_entry.dart';
import 'package:salat_tracker/features/prayer/domain/models/prayer_type.dart';
import 'package:salat_tracker/features/settings/domain/models/app_theme_mode.dart';
import 'package:salat_tracker/features/settings/domain/models/settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeModeAdapter());
    registerAdapter(PrayerDayAdapter());
    registerAdapter(PrayerEntryAdapter());
    registerAdapter(PrayerTypeAdapter());
    registerAdapter(SettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeModeAdapter());
    registerAdapter(PrayerDayAdapter());
    registerAdapter(PrayerEntryAdapter());
    registerAdapter(PrayerTypeAdapter());
    registerAdapter(SettingsAdapter());
  }
}
